import type { NewsArticle } from "../types";

export const newsSeed: NewsArticle[] = [
  {
    id: "news_1",
    slug: "caea-b2b-platform-launch",
    title: {
      kk: "ОАКҚ B2B платформасының жаңа нұсқасы іске қосылды",
      ru: "Запущена новая версия B2B-платформы ЦАКП",
      en: "CAEA launches a new version of its B2B platform",
    },
    excerpt: {
      kk: "Серіктестер каталогы, ақылды сүзгілер және авто-скоринг енгізілді — мүшелер енді бірнеше минутта тиісті серіктесті табады.",
      ru: "Внедрены каталог партнёров, умные фильтры и авто-скоринг — теперь члены находят подходящего партнёра за пару минут.",
      en: "A partner catalog, smart filters and auto-scoring have been introduced — members can now find the right partner in minutes.",
    },
    body: {
      kk: "ОАКҚ B2B платформасының жаңартылған нұсқасы серіктестерді елі, саласы, серіктестік типі және верификация деңгейі бойынша сүзу мүмкіндігін қосты. Авто-скоринг алгоритмі арқасында жаңа серіктес өтінімдерінің 60%-ы адам араласуынсыз бекітіледі.",
      ru: "Обновлённая версия B2B-платформы ЦАКП добавила возможность фильтрации партнёров по стране, отрасли, типу партнёрства и уровню верификации. Благодаря алгоритму авто-скоринга 60% новых заявок партнёров одобряются без участия человека.",
      en: "The updated CAEA B2B platform adds filtering by country, industry, partnership type and verification level. Thanks to the auto-scoring algorithm, 60% of new partner applications are now approved without human review.",
    },
    cover: "/images/bg/dashboard-presentation.webp",
    category: "Платформа",
    author: "ОАКҚ баспасөз қызметі",
    publishedAt: "2025-09-02",
    status: "published",
    minutesToRead: 4,
  },
  {
    id: "news_2",
    slug: "export-roadmap-2026",
    title: {
      kk: "2026 жылға арналған Экспорт жол картасы жарияланды",
      ru: "Опубликована Дорожная карта экспорта на 2026 год",
      en: "The 2026 Export Roadmap has been published",
    },
    excerpt: {
      kk: "Қытай, Түркия және Парсы шығанағы елдеріне бағытталған жаңа экспорт бағдарламасы мүшелерге тегін қолжетімді.",
      ru: "Новая программа экспорта, ориентированная на Китай, Турцию и страны Персидского залива, доступна членам бесплатно.",
      en: "A new export program focused on China, Turkey and the Gulf states is now free for members.",
    },
    body: {
      kk: "Жол картасы кеден рәсімдерін жеңілдету, логистикалық серіктестермен келісім және сертификаттау құнын төмендету бағыттарын қамтиды.",
      ru: "Дорожная карта включает упрощение таможенных процедур, договорённости с логистическими партнёрами и снижение стоимости сертификации.",
      en: "The roadmap covers simplified customs procedures, agreements with logistics partners and reduced certification costs.",
    },
    cover: "/images/bg/meeting-room.webp",
    category: "Экспорт",
    author: "Экспорт бөлімі",
    publishedAt: "2025-10-14",
    status: "published",
    minutesToRead: 6,
  },
  {
    id: "news_3",
    slug: "investor-database-500",
    title: {
      kk: "Инвестор базасы 500-ден асты",
      ru: "База инвесторов превысила 500",
      en: "Investor database surpasses 500",
    },
    excerpt: {
      kk: "PREMIUM және PLATINUM мүшелері енді тексерілген инвесторлардың кеңейтілген тізіміне қол жеткізе алады.",
      ru: "Члены PREMIUM и PLATINUM теперь имеют доступ к расширенному списку проверенных инвесторов.",
      en: "PREMIUM and PLATINUM members now have access to an expanded list of vetted investors.",
    },
    body: {
      kk: "2025 жылғы үшінші тоқсанда инвестор базасы Қазақстан, Өзбекстан және ОАЭ-дегі жаңа қор серіктестерінің есебінен ұлғайды.",
      ru: "В третьем квартале 2025 года база инвесторов выросла за счёт новых фондов-партнёров из Казахстана, Узбекистана и ОАЭ.",
      en: "In Q3 2025, the investor database grew thanks to new fund partners from Kazakhstan, Uzbekistan and the UAE.",
    },
    cover: "/images/bg/boardroom-analytics.webp",
    category: "Инвестиция",
    author: "Инвестиция бөлімі",
    publishedAt: "2025-11-03",
    status: "published",
    minutesToRead: 3,
  },
  {
    id: "news_4",
    slug: "ai-audit-program",
    title: {
      kk: "Шағын бизнес үшін тегін AI-аудит бағдарламасы",
      ru: "Бесплатная программа AI-аудита для малого бизнеса",
      en: "Free AI-audit program for small businesses",
    },
    excerpt: {
      kk: "STANDART тарифінен бастап мүшелер цифрлық жетілу деңгейін тегін бағалай алады.",
      ru: "Начиная с тарифа STANDART члены могут бесплатно оценить уровень цифровой зрелости.",
      en: "Starting from the STANDART plan, members can get a free digital-maturity assessment.",
    },
    body: {
      kk: "Бағдарлама компанияның CRM, аналитика және автоматтандыру деңгейін бағалап, нақты ұсыныстар тізімін береді.",
      ru: "Программа оценивает уровень CRM, аналитики и автоматизации компании и выдаёт конкретный список рекомендаций.",
      en: "The program assesses a company's CRM, analytics and automation maturity and produces a concrete list of recommendations.",
    },
    cover: "/images/bg/dashboard-presentation.webp",
    category: "ЖИ / Digital",
    author: "Digital бөлімі",
    publishedAt: "2025-12-01",
    status: "published",
    minutesToRead: 5,
  },
  {
    id: "news_5",
    slug: "b5plus1-forum-recap",
    title: {
      kk: "B5+1 форумынан кейінгі қорытынды",
      ru: "Итоги форума B5+1",
      en: "B5+1 Forum recap",
    },
    excerpt: {
      kk: "5 елден 250+ өкіл қатысқан форумда ОАКҚ мүшелері жаңа серіктестік келісімдеріне қол жеткізді.",
      ru: "На форуме с участием 250+ представителей из 5 стран члены ЦАКП заключили новые партнёрские соглашения.",
      en: "At the forum, attended by 250+ delegates from 5 countries, CAEA members secured new partnership agreements.",
    },
    body: {
      kk: "Алматыда өткен форум аясында 30-дан астам B2B кездесу ұйымдастырылды және 12 меморандумға қол қойылды.",
      ru: "В рамках форума в Алматы было организовано более 30 B2B-встреч и подписано 12 меморандумов.",
      en: "More than 30 B2B meetings were held and 12 memoranda signed during the Almaty forum.",
    },
    cover: "/images/bg/handshake-network.webp",
    category: "Іс-шара",
    author: "Іс-шаралар бөлімі",
    publishedAt: "2025-12-20",
    status: "published",
    minutesToRead: 4,
  },
  {
    id: "news_6",
    slug: "membership-growth-q1",
    title: {
      kk: "Бірінші тоқсанда мүшелік саны 35%-ға өсті",
      ru: "Число членов выросло на 35% за первый квартал",
      en: "Membership grew 35% in the first quarter",
    },
    excerpt: {
      kk: "Жаңа онбординг процесі мен серіктес автоматты тіркеу модулі тіркелу уақытын 3 есе қысқартты.",
      ru: "Новый процесс онбординга и модуль автоматической регистрации партнёров сократили время регистрации в 3 раза.",
      en: "The new onboarding flow and automated partner registration module cut sign-up time threefold.",
    },
    body: {
      kk: "STANDART және PREMIUM тарифтеріне сұраныс әсіресе IT және логистика салаларында артты.",
      ru: "Спрос на тарифы STANDART и PREMIUM особенно вырос в сферах IT и логистики.",
      en: "Demand for STANDART and PREMIUM plans grew especially fast in the IT and logistics sectors.",
    },
    cover: "/images/bg/meeting-room.webp",
    category: "Қауымдастық",
    author: "ОАКҚ баспасөз қызметі",
    publishedAt: "2026-02-10",
    status: "published",
    minutesToRead: 3,
  },
];
