import type { TariffPlan } from "../types";

export const tariffsSeed: TariffPlan[] = [
  {
    id: "tariff_start",
    code: "START",
    name: "START",
    priceMonth: 0,
    priceYear: 0,
    highlight: false,
    description: {
      kk: "Каталогта профиль ашу және базалық мүмкіндіктерді сынап көру үшін",
      ru: "Чтобы создать профиль в каталоге и попробовать базовые возможности",
      en: "To open a catalog profile and try the basic features",
    },
    features: [
      { label: { kk: "Профиль жасау", ru: "Создание профиля", en: "Create a profile" }, included: true },
      { label: { kk: "Каталогта көріну", ru: "Видимость в каталоге", en: "Catalog visibility" }, included: true },
      { label: { kk: "Кіріс байланыс", ru: "Входящие обращения", en: "Incoming inquiries" }, included: "5 / ай" },
      { label: { kk: "B2B байланыс жіберу", ru: "Отправка B2B-обращений", en: "Send B2B inquiries" }, included: "3 / ай" },
      { label: { kk: "Тендер хабары", ru: "Уведомления о тендерах", en: "Tender alerts" }, included: false },
      { label: { kk: "Аналитика", ru: "Аналитика", en: "Analytics" }, included: false },
      { label: { kk: "Жеке менеджер", ru: "Персональный менеджер", en: "Personal manager" }, included: false },
      { label: { kk: "2FA қауіпсіздік", ru: "2FA безопасность", en: "2FA security" }, included: false },
    ],
  },
  {
    id: "tariff_standart",
    code: "STANDART",
    name: "STANDART",
    priceMonth: 24900,
    priceYear: 249000,
    highlight: false,
    description: {
      kk: "B2B матчмейкинг пен тендер хабарламасы қажет белсенді кәсіпкерлер үшін",
      ru: "Для активных предпринимателей, которым нужны B2B-мэтчмейкинг и тендеры",
      en: "For active entrepreneurs who need B2B matchmaking and tender alerts",
    },
    features: [
      { label: { kk: "Профиль жасау", ru: "Создание профиля", en: "Create a profile" }, included: true },
      { label: { kk: "Каталогта көріну", ru: "Видимость в каталоге", en: "Catalog visibility" }, included: true },
      { label: { kk: "Кіріс байланыс", ru: "Входящие обращения", en: "Incoming inquiries" }, included: "50 / ай" },
      { label: { kk: "B2B байланыс жіберу", ru: "Отправка B2B-обращений", en: "Send B2B inquiries" }, included: "30 / ай" },
      { label: { kk: "Тендер хабары", ru: "Уведомления о тендерах", en: "Tender alerts" }, included: true },
      { label: { kk: "Аналитика", ru: "Аналитика", en: "Analytics" }, included: "Базалық" },
      { label: { kk: "Жеке менеджер", ru: "Персональный менеджер", en: "Personal manager" }, included: false },
      { label: { kk: "2FA қауіпсіздік", ru: "2FA безопасность", en: "2FA security" }, included: true },
    ],
  },
  {
    id: "tariff_premium",
    code: "PREMIUM",
    name: "PREMIUM",
    priceMonth: 79900,
    priceYear: 799000,
    highlight: true,
    description: {
      kk: "Экспорт сүйемелдеу мен инвестор байланысы қажет өсу сатысындағы бизнес үшін",
      ru: "Для растущего бизнеса, которому нужны экспортное сопровождение и связь с инвесторами",
      en: "For growing businesses needing export support and investor introductions",
    },
    features: [
      { label: { kk: "Профиль жасау", ru: "Создание профиля", en: "Create a profile" }, included: true },
      { label: { kk: "Каталогта көріну", ru: "Видимость в каталоге", en: "Catalog visibility" }, included: true },
      { label: { kk: "Кіріс байланыс", ru: "Входящие обращения", en: "Incoming inquiries" }, included: "Шексіз" },
      { label: { kk: "B2B байланыс жіберу", ru: "Отправка B2B-обращений", en: "Send B2B inquiries" }, included: "Шексіз" },
      { label: { kk: "Тендер хабары", ru: "Уведомления о тендерах", en: "Tender alerts" }, included: true },
      { label: { kk: "Аналитика", ru: "Аналитика", en: "Analytics" }, included: "Толық" },
      { label: { kk: "Жеке менеджер", ru: "Персональный менеджер", en: "Personal manager" }, included: true },
      { label: { kk: "2FA қауіпсіздік", ru: "2FA безопасность", en: "2FA security" }, included: true },
    ],
  },
  {
    id: "tariff_platinum",
    code: "PLATINUM",
    name: "PLATINUM",
    priceMonth: null,
    priceYear: null,
    highlight: false,
    description: {
      kk: "Корпоративтік брендинг пен стратегиялық серіктестік қажет ірі компанияларға",
      ru: "Для крупных компаний, нуждающихся в корпоративном брендинге и стратегическом партнёрстве",
      en: "For large companies needing corporate branding and strategic partnership",
    },
    features: [
      { label: { kk: "Профиль жасау", ru: "Создание профиля", en: "Create a profile" }, included: true },
      { label: { kk: "Каталогта көріну", ru: "Видимость в каталоге", en: "Catalog visibility" }, included: true },
      { label: { kk: "Кіріс байланыс", ru: "Входящие обращения", en: "Incoming inquiries" }, included: "Шексіз" },
      { label: { kk: "B2B байланыс жіберу", ru: "Отправка B2B-обращений", en: "Send B2B inquiries" }, included: "Шексіз" },
      { label: { kk: "Тендер хабары", ru: "Уведомления о тендерах", en: "Tender alerts" }, included: true },
      { label: { kk: "Аналитика", ru: "Аналитика", en: "Analytics" }, included: "Толық+" },
      { label: { kk: "Жеке менеджер", ru: "Персональный менеджер", en: "Personal manager" }, included: true },
      { label: { kk: "Featured (алдыңғы)", ru: "Featured (приоритет)", en: "Featured placement" }, included: true },
      { label: { kk: "2FA қауіпсіздік", ru: "2FA безопасность", en: "2FA security" }, included: true },
    ],
  },
  {
    id: "tariff_academy",
    code: "ACADEMY",
    name: "ACADEMY",
    priceMonth: null,
    priceYear: null,
    highlight: false,
    description: {
      kk: "ЖОО мен зерттеу орталықтары үшін: R&D, стартап экожүйесі, грант навигация",
      ru: "Для вузов и исследовательских центров: R&D, стартап-экосистема, навигация по грантам",
      en: "For universities and research centers: R&D, startup ecosystem, grant navigation",
    },
    features: [
      { label: { kk: "Профиль жасау", ru: "Создание профиля", en: "Create a profile" }, included: true },
      { label: { kk: "R&D серіктестік қолжетімділігі", ru: "Доступ к R&D-партнёрству", en: "R&D partnership access" }, included: true },
      { label: { kk: "Стартап акселератор", ru: "Стартап-акселератор", en: "Startup accelerator" }, included: true },
      { label: { kk: "Грант навигация", ru: "Навигация по грантам", en: "Grant navigation" }, included: true },
      { label: { kk: "Жеке менеджер", ru: "Персональный менеджер", en: "Personal manager" }, included: true },
    ],
  },
];
