import type { Tender } from "../types";

export const tendersSeed: Tender[] = [
  {
    id: "tender_1",
    title: "Ауыл шаруашылығы техникасын жеткізу",
    organization: "Алматы облысы әкімдігі",
    amount: 145000000,
    currency: "KZT",
    deadline: "2026-07-20",
    industry: "Агро",
    country: "KZ",
    source: "goszakup.kz",
    createdAt: "2026-06-10",
  },
  {
    id: "tender_2",
    title: "Логистика орталығының IT инфраструктурасы",
    organization: "ҰлттыұQ Logistics LLP",
    amount: 62000000,
    currency: "KZT",
    deadline: "2026-07-05",
    industry: "Логистика",
    country: "KZ",
    source: "goszakup.kz",
    createdAt: "2026-06-08",
  },
  {
    id: "tender_3",
    title: "Тоқыма өнімдерін мемлекеттік сатып алу",
    organization: "Әлеуметтік қолдау қоры",
    amount: 38500000,
    currency: "KZT",
    deadline: "2026-06-30",
    industry: "Өнеркәсіп",
    country: "KZ",
    source: "goszakup.kz",
    createdAt: "2026-06-05",
  },
  {
    id: "tender_4",
    title: "Қала көшелерін жарықтандыру жобасы",
    organization: "Шымкент қаласы әкімдігі",
    amount: 210000000,
    currency: "KZT",
    deadline: "2026-08-12",
    industry: "Құрылыс",
    country: "KZ",
    source: "goszakup.kz",
    createdAt: "2026-06-12",
  },
  {
    id: "tender_5",
    title: "Тоштут вилоятида IT хизматларини етказиб бериш",
    organization: "Toshkent shahar hokimligi",
    amount: 480000000,
    currency: "UZS",
    deadline: "2026-07-15",
    industry: "IT",
    country: "UZ",
    source: "uzex.uz",
    createdAt: "2026-06-09",
  },
  {
    id: "tender_6",
    title: "Медициналық жабдықтарды жеткізу",
    organization: "Алматы қалалық денсаулық сақтау басқармасы",
    amount: 96000000,
    currency: "KZT",
    deadline: "2026-07-28",
    industry: "Медицина",
    country: "KZ",
    source: "goszakup.kz",
    createdAt: "2026-06-14",
  },
];
